name: calendar
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  flutter_svg:
  syncfusion_flutter_sliders: ^26.2.14
  paged_vertical_calendar: ^1.1.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  flutter_gen: ^5.7.0

flutter:
  uses-material-design: true
  assets: 
    - assets/svg/
    - assets/png/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/static/Nunito-ExtraBold.ttf
        - asset: assets/fonts/static/Nunito-Regular.ttf
        - asset: assets/fonts/static/Nunito-Light.ttf
        - asset: assets/fonts/static/Nunito-Medium.ttf